### ISSUE TITLE
Lack of perl module

### ISSUE THREAD

**Issue by lizihe21** [hillerlab/GeneLossPipe#1]
Hi,
I was trying to run the pipeline and the errors shows requirement of a number of .pm file which are not in the src dir.For example, MyKentFunctions.pm MyFunctions.pm, these modules are shown in "$ENV{'genomePath'}/src/LabPerlModules" according to the .pm file in src dir.Could you please upload these perl module?
Thanks.

**Comment by MichaelHiller** [comment]
Hi,
I have uploaded both modules. 
There will be a revamped gene loss pipeline integrated in our new TOGA (Tool to infer Orthologs from Genome Alignments) method, which we will release soon. 

Best
Michael

**Comment by lizihe21** [comment]
> Hi,
> I have uploaded both modules.
> There will be a revamped gene loss pipeline integrated in our new TOGA (Tool to infer Orthologs from Genome Alignments) method, which we will release soon.
> 
> Best
> Michael

Thanks for responding.
There are still lack of MyBDB.pm ,FixInsertsFromILines.pm,MyMaxEnt.pm used by further step.
We used CESAR2 to call orthologs now. What improvement will TOGA get?
Best

**Comment by MichaelHiller** [comment]
Please comment out these My*pm lines in MyFunctions and MyKentFunctions. I believe they are not needed. TOGA is also using CESAR2.0 but has a variety of other features, a new approach to determine orthologs, and an improved gene loss module.
Best
Michael
