### ISSUE TITLE
Situation of perl script "MergeBDB.perl "

### ISSUE THREAD

**Issue by zxclovezby** [hillerlab/GeneLossPipe#2]
Hi,
I am learning the gene loss pipeline recently, I found a perl script  "MergeBDB.perl" be mentioned in step 4 "Realignment with CESAR " and step 6 "Detecting mutations in pairwise alignments", but I couldn't found the script in the src dir, I wonder which script has the similar function with "MergeBDB.perl" or could you please upload this scrpit? 
Sincerely.
zxczxc

**Comment by MichaelHiller** [comment]
Hi, 
I added the script. 
Please consider running our TOGA https://github.com/hillerlab/TOGA method, which also implements an improved gene loss pipeline (and annotates genes and orthologs).

**Comment by zxclovezby** [comment]
Hi,
I noticed the function of TOGA, it's really amazing, and I'll learn and run it, Thanks for your apply.
